### PR TITLE
Show header navigation in its entiety on Safari

### LINKED ISSUE #65: Header content and icons  not showing in safari browser
Open https://croma.app on the safari browser. You will notice  header content and icons are not showing in the safari browser 

**On Safari** 
Screen Shot 2020-04-28 at 12 29 33 PM

**On Chrome**
Screen Shot 2020-10-05 at 8 34 35 PM

### PR DESCRIPTION
**Pull request by ashokaditya**
fixes #65 

**Screenshots (Safari):**
Screenshot 2020-10-19 at 20 12 18
Screenshot 2020-10-19 at 20 11 58
Screenshot 2020-10-19 at 20 14 46

### CODE REVIEW

**Comment by ashokaditya** [comment]
@bhujoshi please add a `hacktoberfest-accepted` label to this if all good. Or add `hacktoberfest` as a topic to your repo.

**Comment by kamalkishor1991** [comment]
@ashokaditya thanks a lot for sending a fix. I added hacktoberfest as a topic. 
Can you please add more details on what is the issue and why do we have to add it to all the screen components? 
Seems really unmaintainable to add it to all the components right?

**Comment by ashokaditya** [comment]
@kamalkishor1991 thanks for following up.
So as I see it the Safari bug is due to the fact that there's a `max-width` set on top of the app content at the `View` node which is shared for native and web apps. The rest of the app is configured via [React Navigation](https://github.com/croma-app/croma-react/blob/5c12d3d62762f0bf844a4d82556c5c43b941cec3/navigation/MainTabNavigator.js#L25)
 that have components mapped to corresponding route names. If this was not the case I could have encapsulated these components into a top component and added the styles to only that. But doing that would be a big change. 

So I went with a smaller change. The idea was to then render the app content in its full width (which is within the top `View`) and add a `max-width` restriction to the content that renders below the header. Mot using React Navigation and writing a custom navigation component would be a better approach in my opinion. But this is also a big change.

**Comment by kamalkishor1991** [comment]
@ashokaditya thanks for the explanation,  I still don't understand why it is only a problem with safari. Can you send me an email and I can add you to the slack group to discuss this more?
email: kkjoshi.it@gmail.com

**Comment by ashokaditya** [comment]
@kamalkishor1991 thanks for asking the relevant questions which led me to look into it bit closer. I found a simpler more maintainable fix after all. At least compared to the previous one. Essentially React Navigation adds styles that Safari renders differently than Chrome or Firefox. This fix overrides the react navigation style, particularly `overflow` so that the header is visible in its entirety.

**Review by kamalkishor1991 — APPROVED** [review]

**Comment by kamalkishor1991** [comment]
Looks good. Thanks

**Comment by ashokaditya** [comment]
👍 thanks @kamalkishor1991

**Pull request merged**
