### PR TITLE
Migration to react-navigation v5

### PR DESCRIPTION
**Pull request by EduardoFLima**
Main changes:

- Replaced old sidebar menu solution per react-navigation own solution (drawer navigator);
- In order to keep the header and the sidebar menu (which is there just for android), two navigators were nested (under the drawer navigator there is a stack navigator). For web/ios there is just a stack navigator;
- Because of the nested navigators, replaced of all `navigation.setParam/navigation.getParam` per context variables - this way there is a better handle of the navigators params (this was the advisable thing to do according some examples and blog posts over the internet)

I tested everything and it seems ok but please help to test it, there were a lot of changes. I was not able to test on IOS.

Another solution for the nested navigators thing would be to create the headers by our own. This is also an option and we could stick using `navigation.params`

### CODE REVIEW

**Comment by kamalkishor1991** [comment]
Hey thanks a lot for this. I will spend some time understanding and testing this. On vacation for next 10 days. Will check it immediately after that.

**Comment by bhujoshi** [comment]
@EduardoFLima Everything seems good on the android app. Just one icon is broken for **scan color codes** have a look at the below screenshot.
But the web is totally broken try to run web using `npm run web` 
Let me know in case any help needed from me. Thanks again for your time and effects.
scan-color-doe-icon-missing
.

**Comment by EduardoFLima** [comment]
Hey @bhujoshi , 

I had to update `@expo/vector-icons` because of react-navigation bump. I thought it was something happening just in my side... 

Just checked that apparently this is a vector-icons bug and even there is a [bug opened](https://github.com/expo/vector-icons/issues/135) for that. Even in [their page](https://icons.expo.fyi/MaterialCommunityIcons/credit-card-scan) it appears to be failing:

image


Is it possible to change by [credit-card-scan-outline](https://icons.expo.fyi/MaterialCommunityIcons/credit-card-scan-outline) or any other scan icon ?

**Comment by bhujoshi** [comment]
@EduardoFLima Yeah! We can change it to `credit-card-scan-outline`.

**Comment by kamalkishor1991** [comment]
@EduardoFLima any progress with web support? Let me know if you need a second pair of eyes for debugging anything or need any help.

**Comment by EduardoFLima** [comment]
Hi there !
Sorry, I completely missed that sentence saying the web is broken.
In my side is working just fine, I did many tests there - I just couldn't test IOS... would you try to run npm install and clear cache ?

image

**Comment by bhujoshi** [comment]
@EduardoFLima Thanks Yes it is working correctly on the web as well. Earlier I think I have done some mistakes in testing.
About IOS we are only on Android and Web for now. We are planning to release on IOS soon.

**Pull request merged**
