### PR TITLE
Add "about us" screen for android

### PR DESCRIPTION
**Pull request by EduardoFLima**
Added "about us" screen for android.

Apart from that, 2 other changes:

- Added usesCleartextTraffic to android manifest in order to being able to connect metro packager with the app.
- Refactored some StyleSheet.create() methods, they were throwing erros when running the app in the android emulator due some invalid properties that should be applied only to a 'web' platform

### CODE REVIEW

**Comment by kamalkishor1991** [comment]
Thanks a lot for this. This looks great. Few suggestions
1. can we move "About Us" title to header?
2. Can we add a web link also saying "Lightweight web version to preview and share palettes"?

Screenshot from 2020-10-19 07-20-30

**Comment by EduardoFLima** [comment]
Done... please have a look.

I wasn't sure what url add to the new link so I added https://croma.app/#/. Please let me know if this is the one.

**Review by kamalkishor1991 — APPROVED** [review]

**Comment by kamalkishor1991** [comment]
@EduardoFLima thanks again for taking care of this. I have released this to the play store. You should be able to see your change in the play store soon.

**Comment by EduardoFLima** [comment]
@kamalkishor1991 glad I could help !

Is it possible to add the "hacktoberfest" topic to the repo so it would count to [digital oceans' hacktoberfest](https://hacktoberfest.digitalocean.com/profile) ?

**Comment by kamalkishor1991** [comment]
@EduardoFLima added already. Can you please check again.

**Pull request merged**
